name: Check Community Timers
on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch: # Zaka iya danna 'Run' da kanka don gwadawa

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install firebase-admin
      - env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python notify_testers.py
